#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KodiAndroid.Resource", IsApplication=true)]

namespace KodiAndroid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int blank_title = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int Border = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int default_button = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int default_button_pressed = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int default_button_selector = 2130771972;
			
			// aapt resource value: 0x7F01000B
			public const int Icon = 2130771979;
			
			// aapt resource value: 0x7F010005
			public const int ic_action_content_create = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ic_action_content_save = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int ic_menu_copy_holo_dark = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int ic_menu_cut_holo_dark = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int ic_menu_paste_holo_dark = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int ic_menu_search_holo_dark = 2130771978;
			
			// aapt resource value: 0x7F01000C
			public const int Kodi_logo = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int mute_off = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int mute_on = 2130771982;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020009
			public const int about = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int aboutInfoFB = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int aboutText = 2130837515;
			
			// aapt resource value: 0x7F020000
			public const int AboutToolbar = 2130837504;
			
			// aapt resource value: 0x7F02000C
			public const int aboutToolbarText = 2130837516;
			
			// aapt resource value: 0x7F020001
			public const int ApiUnr = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int BackButton = 2130837506;
			
			// aapt resource value: 0x7F02000D
			public const int downButton = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int forwardButton = 2130837518;
			
			// aapt resource value: 0x7F020003
			public const int HomeButton = 2130837507;
			
			// aapt resource value: 0x7F02000F
			public const int leftButton = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int mainText = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int menu_preferences = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int muteButton = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int nextButton = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int okButton = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int options = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int playpauseButton = 2130837526;
			
			// aapt resource value: 0x7F020004
			public const int PowerButton = 2130837508;
			
			// aapt resource value: 0x7F020017
			public const int previousButton = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int rewindButton = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int rightButton = 2130837529;
			
			// aapt resource value: 0x7F020005
			public const int SaveOptions = 2130837509;
			
			// aapt resource value: 0x7F02001A
			public const int textView1 = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int toolbar = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int toolbarImg = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int toolbarText = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int upButton = 2130837534;
			
			// aapt resource value: 0x7F020006
			public const int VibraSwitch = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int VolumDownButton = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int VolumUpButton = 2130837512;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int Options = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int Toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F040000
			public const int top_menus = 2130968576;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050012
			public const int aboutFaceBookLinks = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int aboutGitHubLinks = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int aboutText = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int aboutVkontakteLinks = 2131034133;
			
			// aapt resource value: 0x7F050000
			public const int MainBackButton = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int MainDownButton = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int MainForwardButton = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int MainHomeButton = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int MainLeftButton = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int MainNextButton = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int MainOkButton = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int MainPlayButton = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int MainPowerButton = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int MainPrevButton = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int MainRewindButton = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int MainRightButton = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int MainUpButton = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int MainVolumDownButton = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int MainVolumUpButton = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int OptionsSaveButton = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int OptionsVibrationSwitch = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int OptionsWebApiText = 2131034129;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int DefaultButton = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int KodiAndroidTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int Space = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
