#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KodiAndroid.Resource", IsApplication=true)]

namespace KodiAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blank_title = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Border = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int default_button_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int default_button_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_content_create = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_content_save = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_copy_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_cut_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_paste_holo_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_search_holo_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Kodi_logo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int mute_off = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mute_on = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int AboutToolbar = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int ApiUnr = 2131165207;
			
			// aapt resource value: 0x7f070007
			public const int BackButton = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int HomeButton = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int PowerButton = 2131165189;
			
			// aapt resource value: 0x7f070019
			public const int SaveOptions = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int VibraSwitch = 2131165208;
			
			// aapt resource value: 0x7f070013
			public const int VolumDownButton = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int VolumUpButton = 2131165205;
			
			// aapt resource value: 0x7f07001e
			public const int about = 2131165214;
			
			// aapt resource value: 0x7f070003
			public const int aboutInfoFB = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int aboutText = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int aboutToolbarText = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int downButton = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int forwardButton = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int leftButton = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int mainText = 2131165192;
			
			// aapt resource value: 0x7f07001c
			public const int menu_preferences = 2131165212;
			
			// aapt resource value: 0x7f070014
			public const int muteButton = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int nextButton = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int okButton = 2131165200;
			
			// aapt resource value: 0x7f07001d
			public const int options = 2131165213;
			
			// aapt resource value: 0x7f07000b
			public const int playpauseButton = 2131165195;
			
			// aapt resource value: 0x7f070009
			public const int previousButton = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int rewindButton = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int rightButton = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int textView1 = 2131165206;
			
			// aapt resource value: 0x7f070004
			public const int toolbar = 2131165188;
			
			// aapt resource value: 0x7f07001a
			public const int toolbarImg = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int toolbarText = 2131165211;
			
			// aapt resource value: 0x7f07000e
			public const int upButton = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int top_menus = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int aboutFaceBookLinks = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int aboutGitHubLinks = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int aboutText = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int aboutVkontakteLinks = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int DefaultButton = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int KodiAndroidTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
